-- ============================================================
-- chunks.sql —— 已并入 schema.sql（v2.1 基准重写），本文件仅保留占位说明
-- ============================================================
-- 历史：chunks 表最初单独放在本文件（含旧 IVFFlat 索引注释与一条
-- ALTER TABLE ... ADD COLUMN segment）。v2.1 重写基准 DDL 时，
-- chunks 表（含 segment/classified_segment/user_edited/metadata/embedding
-- vector(1024) 与 HNSW 索引）已完整并入 schema.sql。
--
-- 本文件不再包含任何 DDL，保留仅为兼容部署脚本中
-- "db/schema.sql + db/chunks.sql" 的执行顺序引用
-- （见设计文档 12.部署）。新部署只需执行 schema.sql。
-- ============================================================
